### ISSUE TITLE
Uglifyify does not minify node.js' built-in modules

### ISSUE THREAD

**Issue by TuurDutoit** [hughsk/uglifyify#28]
For example, when you `require("events")` in your input file, along with some other modules, everything except the `events` module is minified.
Coudl it be that browserify doesn't pass built-in modules to transforms?

**Comment by ibc** [comment]
`require("events")` means that browserify will insert that module in "compilation" time (replacing the `require` call with the whole module), so any previous action in the code would not take effect as such a code did not yet exist.
