### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ibc** [hughsk/uglifyify#29]
I see 5 interesting PR with no feedback from the author(s). Is this project maintained?

**Comment by jbkly** [comment]
Great question, wondering the same thing.

**Comment by EvanCarroll** [comment]
I'd be willing to jump in and maintain if @hughsk wants out...

**Comment by hughsk** [comment]
@ibc not very actively, unfortunately – uglifyify keeps slipping down my inbox when it comes up. Fortunately I've found a window and have cleaned up the source map issues, hopefully for good.

Sorry @nowells @brycekahle @jheusala @BlueHotDog @erickedji for the delay in reviewing your PRs!

@nowells @timoxley @weilu would any of you be happy for me to add you to the project? No pressure. Sorry @EvanCarroll but generally I wait until receiving a PR before adding contributors, if you run into any issues and submit a fix then I can look into it more promptly this time :)

**Comment by weilu** [comment]
Sure, I'm happy to help out :)

**Comment by hughsk** [comment]
@weilu awesome – thanks! I'll add you now :)
