### ISSUE TITLE
Seems to support some ES6 features and not others?

### ISSUE THREAD

**Issue by isaachinman** [hughsk/uglifyify#49]
So, I have no problem using arrow functions, `const`, and other ES6 features with uglifyify. However, I cannot use `let` _at all_. It produces a `JS_Parse_Error` on compilation.

Here's an example.

**App.js:**

    let thisIsATest = true

**CL:**

    uglifyify src/app.js -o build/app.js

**Error returned:**

    Error
    at new JS_Parse_Error (eval at <anonymous> (/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)

I really like this tool, but also need to be able to write in ES6. Cheers.

**Comment by yoshuawuyts** [comment]
This is because uglifyjs doesn't support all of ES6 yet. Consider running babel / es2020 before minifying your code. Cheers!

**Comment by isaachinman** [comment]
Ah okay, I looked through the documentation but this wasn't immediately obvious. Cheers.
