### ISSUE TITLE
Upgrade Minimatch to v3

### ISSUE THREAD

**Issue by jsonmaur** [hughsk/uglifyify#54]
Minimatch should be upgraded to `v3` to avoid a RegExp DoS issue. We're using uglifyify in Jumpsuit, and get a deprecated warning because of this: https://github.com/jumpsuit/jumpsuit/issues/29

**Comment by jsonmaur** [comment]
Looks like there's already a pull request for this: https://github.com/hughsk/uglifyify/pull/53. @hughsk any update on when this will be merged?

**Comment by KenanY** [comment]
Fixed in `uglifyify@3.0.3`.

**Comment by jsonmaur** [comment]
Great!
