### ISSUE TITLE
Uglifyify fails when calling uglify 

### ISSUE THREAD

**Issue by betalb** [hughsk/uglifyify#78]
If I try to build react, using build instructions from https://facebook.github.io/react/docs/optimizing-performance.html#browserify, build fails with following error:

```
`_flags` is not a supported option
```

After small debugging it turns out that options object that is passed to plugin factory function can be mutated in time, and even if `_flags` property is deleted at the beginning, later, when string buffer is assembled, `_flags` may re-appear

**Comment by cordovapolymer** [comment]
same here. When building [pica](https://github.com/nodeca/pica)

**Comment by kristoferjoseph** [comment]
Same here. Any ideas on how to patch this?

**Comment by pronebird** [comment]
Same issue here.
